name: isotomics-run
channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - numpy=1.23.5
  - pandas=2.0.0
  - tqdm=4.67.3
  - matplotlib=3.10.0
  - seaborn=0.13.0
  - networkx=3.1
  - sympy=1.12
  - scipy=1.14.0
  - pip
  - pip:
      - -e .
